version: '3'

services:
  db_postgres:
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data

  parcial_app:
    build: .
    volumes:
      - static:/code/static
      - .:/code
    depends_on:
      - db_postgres

  nginx:
    image: nginx:1.13
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/code/static
    depends_on:
      - parcial_app
volumes:
  .:
  postgres_data:
  static:
